version: 2
jobs:
  build:
    docker:
      - image: mvukov/bazel-builder:latest
    steps:
      - checkout
      - run:
          name: Build & Test
          command: |
            bazel test -c dbg //...
